### ISSUE TITLE
"Portable version" to paste on Chrome Dev tool and run?

### ISSUE THREAD

**Issue by neonleo** [broofa/checkcss#1]
It is more convenient if it can copy the script, paste on Chrome Dev tool console, press Enter and Run.

**Comment by broofa** [comment]
Try pasting `import('https://cdn.jsdelivr.net/npm/checkcss/index.js').then(m => m.default())` into your console.  Let me know if that works and I'll add it to the README.

edit: This may or may not work depending on the content-policy of the website in question.  I tried it on a StackOverflow page and it worked.  But it fails on (for example) codepen.io.

**Comment by broofa** [comment]
Quick(or _really slow_?) followup...

While the above snippet does work, it only works if a website allows the jsdelivr.net domain as part of it's [CSP policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).  Not many sites actually do that, though, which means it doesn't actually work all that well.

The right approach here is probably to implement this as a browser extension... which is out of scope of this project for the time being.
