### ISSUE TITLE
Missing file warnings when building with typescript

### ISSUE THREAD

**Issue by reporter123** [broofa/checkcss#9]
checkcss  2.0.6 does not include orginal typescript source resuting in the fallowing build warnings from any project using it:

Failed to parse source map from '.../node_modules/checkcss/src/CheckCSS.ts' file: Error: ENOENT: no such file or directory, open '.../node_modules/checkcss/src/CheckCSS.ts'

Failed to parse source map from './node_modules/checkcss/src/index.ts' file: Error: ENOENT: no such file or directory, open '.../node_modules/checkcss/src/index.ts'

Failed to parse source map from '.../node_modules/checkcss/src/util.ts' file: Error: ENOENT: no such file or directory, open '.../node_modules/checkcss/src/util.ts'

**Comment by reporter123** [comment]
It looks like the problem was introduced in 2.0.2. This commit looks like the cause https://github.com/broofa/checkcss/commit/f3fa0ac2e456cc817618609d044d588aa4e69cd6

**Comment by broofa** [comment]
Added src files back into package.  Released as `checkcss@2.0.7`.  Give it a try and let me know if you're still seeing this issue.

**Comment by reporter123** [comment]
That did it.
